unique_ids:
  assets:
    standard-page.html: KT2TBJGH6SDEOOE5VAQJWKVBR4R27AA2
    theme.css: CHJVRSM4LU76ZBWMFFIRA72CIYSG24U5
  forms:
    Form1: XMVMZWT23Z6KMYQ27VZ7UEEH73VXGAUW
  modules: {}
  scripts: {}
  server_modules: {}
